// story-generator/framework-adapters/web-components-adapter.ts
/**
 * Web Components Framework Adapter
 *
 * Generates Storybook stories for Web Components (Lit, vanilla, etc.).
 * Supports standard Web Components and Lit framework.
 */

import {
  FrameworkType,
  StoryFramework,
  StoryGenerationOptions,
} from './types.js';
import { BaseFrameworkAdapter } from './base-adapter.js';
import { StoryUIConfig } from '../../story-ui.config.js';
import { DiscoveredComponent } from '../componentDiscovery.js';

export class WebComponentsAdapter extends BaseFrameworkAdapter {
  readonly type: FrameworkType = 'web-components';
  readonly name = 'Web Components';
  readonly supportedStoryFrameworks: StoryFramework[] = [
    'storybook-web-components',
    'chromatic',
  ];
  readonly defaultExtension = '.stories.ts';

  generateSystemPrompt(
    config: StoryUIConfig,
    options?: StoryGenerationOptions
  ): string {
    if (config.systemPrompt) {
      return config.systemPrompt;
    }

    const componentSystemName = config.componentPrefix
      ? `${config.componentPrefix.replace(/^[A-Z]+/, '')} design system`
      : 'component library';

    return `You are an expert Web Components developer creating Storybook stories using CSF 3.0 format.
Use ONLY the Web Components from the ${componentSystemName} listed below.

MANDATORY IMPORTS - First lines of every story file:
1. import { html } from 'lit';
2. import type { Meta, StoryObj } from '@storybook/web-components';
3. import '${config.importPath || 'your-library'}'; // Register custom elements

WEB COMPONENTS STORY FORMAT:
- Use the html template literal from Lit for rendering
- Custom elements use kebab-case tag names (e.g., <my-button>)
- Properties are set as attributes or with . prefix for property binding
- Events use @ prefix (e.g., @click)

COMPONENT REGISTRATION:
- Web Components must be registered before use
- Import the component file to auto-register: import 'my-library/my-button';
- Or import the class and define: customElements.define('my-button', MyButton);

STORY STRUCTURE (CSF 3.0):
- Meta object with title and optional component reference
- Use render function with html\`\` template literal
- Export named stories as StoryObj

CRITICAL RULES:
- Use html template literal, NOT JSX
- Use kebab-case for tag names
- Use .property for property binding, attribute for attributes
- Use @event for event handlers

Example structure:
\`\`\`typescript
import { html } from 'lit';
import type { Meta, StoryObj } from '@storybook/web-components';
import 'your-library/button';

const meta: Meta = {
  title: 'Components/Button',
  tags: ['autodocs'],
  argTypes: {
    variant: {
      control: 'select',
      options: ['primary', 'secondary', 'ghost'],
    },
  },
};

export default meta;
type Story = StoryObj;

export const Primary: Story = {
  args: { variant: 'primary' },
  render: (args) => html\`
    <my-button variant=\${args.variant}>
      Click me
    </my-button>
  \`,
};

export const WithIcon: Story = {
  render: () => html\`
    <my-button variant="primary">
      <my-icon slot="icon" name="star"></my-icon>
      Starred
    </my-button>
  \`,
};
\`\`\`

ATTRIBUTE VS PROPERTY BINDING:
- Attributes (string values): variant="primary"
- Properties (any value): .disabled=\${true}
- Boolean attributes: ?disabled=\${true}
- Events: @click=\${handleClick}

SLOTS:
- Default slot: Content between tags
- Named slots: Use slot="name" attribute
- Example: <my-card><span slot="header">Title</span>Content</my-card>

${this.getCommonRules()}`;
  }

  generateExamples(config: StoryUIConfig): string {
    const lib = config.importPath || 'your-library';

    return `
## Example Stories for Web Components

### Single Component Story
\`\`\`typescript
import { html } from 'lit';
import type { Meta, StoryObj } from '@storybook/web-components';
import 'your-library/button';

const meta: Meta = {
  title: 'Components/Button',
  tags: ['autodocs'],
  argTypes: {
    variant: {
      control: 'select',
      options: ['primary', 'secondary', 'ghost'],
    },
    size: {
      control: 'select',
      options: ['small', 'medium', 'large'],
    },
  },
};

export default meta;
type Story = StoryObj;

export const Default: Story = {
  args: { variant: 'primary', size: 'medium' },
  render: (args) => html\`
    <my-button
      variant=\${args.variant}
      size=\${args.size}
    >
      Button
    </my-button>
  \`,
};

export const Disabled: Story = {
  render: () => html\`
    <my-button variant="primary" ?disabled=\${true}>
      Disabled Button
    </my-button>
  \`,
};
\`\`\`

### Layout Story (Multiple Components)
\`\`\`typescript
import { html } from 'lit';
import type { Meta, StoryObj } from '@storybook/web-components';
import '${lib}/card';
import 'your-library/button';
import '${lib}/text';

const meta: Meta = {
  title: 'Examples/Card Layout',
  parameters: { layout: 'padded' },
};

export default meta;
type Story = StoryObj;

export const ProductCard: Story = {
  render: () => html\`
    <my-card style="width: 300px">
      <img slot="media" src="https://picsum.photos/300/200" alt="Product">
      <span slot="header">Product Name</span>
      <my-text>$99.00</my-text>
      <my-button slot="footer" variant="primary">Add to Cart</my-button>
    </my-card>
  \`,
};
\`\`\`

### With Event Handling
\`\`\`typescript
import { html } from 'lit';
import type { Meta, StoryObj } from '@storybook/web-components';
import 'your-library/button';

const meta: Meta = {
  title: 'Components/Button',
};

export default meta;
type Story = StoryObj;

export const WithClickHandler: Story = {
  render: () => html\`
    <my-button
      variant="primary"
      @click=\${(e: Event) => console.log('Clicked!', e)}
    >
      Click me
    </my-button>
  \`,
};
\`\`\`
`;
  }

  generateSampleStory(
    config: StoryUIConfig,
    components: DiscoveredComponent[]
  ): string {
    const lib = config.importPath || 'your-library';
    const firstComponent = components[0];

    if (!firstComponent) {
      return `
import { html } from 'lit';
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Examples/Sample',
  parameters: { layout: 'centered' },
};

export default meta;
type Story = StoryObj;

export const Default: Story = {
  render: () => html\`<div>Sample story content</div>\`,
};
`;
    }

    // Convert PascalCase to kebab-case for tag name
    const tagName = this.toKebabCase(firstComponent.name);

    return `
import { html } from 'lit';
import type { Meta, StoryObj } from '@storybook/web-components';
import '${lib}/${tagName}';

const meta: Meta = {
  title: 'Components/${firstComponent.name}',
  tags: ['autodocs'],
  parameters: { layout: 'centered' },
};

export default meta;
type Story = StoryObj;

export const Default: Story = {
  render: () => html\`<${tagName}></${tagName}>\`,
};
`;
  }

  getStoryTemplate(options?: StoryGenerationOptions): string {
    return `
// {{componentName}}.stories.ts
import { html } from 'lit';
import type { Meta, StoryObj } from '@storybook/web-components';
import '{{importPath}}';

const meta: Meta = {
  title: '{{category}}/{{componentName}}',
  tags: ['autodocs'],
  parameters: { layout: 'centered' },
};

export default meta;
type Story = StoryObj;

export const Default: Story = {
  render: () => html\`<{{tagName}}></{{tagName}}>\`,
};
`;
  }

  /**
   * Convert PascalCase to kebab-case
   */
  private toKebabCase(str: string): string {
    return str
      .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
      .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
      .toLowerCase();
  }

  /**
   * Post-process Web Components stories
   */
  postProcess(storyContent: string): string {
    let processed = super.postProcess(storyContent);

    // Ensure lit import is present
    if (!processed.includes("import { html } from 'lit'")) {
      processed = "import { html } from 'lit';\n" + processed;
    }

    // Fix common issues
    processed = processed
      // Remove React-style className
      .replace(/className=/g, 'class=')
      // Fix JSX-style event handlers
      .replace(/onClick=/g, '@click=')
      .replace(/onChange=/g, '@change=')
      .replace(/onInput=/g, '@input=');

    return processed;
  }

  /**
   * Validate Web Components story
   */
  validate(storyContent: string): { valid: boolean; errors: string[] } {
    const baseValidation = super.validate(storyContent);
    const errors = [...baseValidation.errors];

    // Web Components specific validations
    if (!storyContent.includes("import { html } from 'lit'")) {
      errors.push("Missing 'import { html } from 'lit'' statement");
    }

    if (storyContent.includes('import React')) {
      errors.push('React import found in Web Components story');
    }

    // Check for JSX syntax (should use lit html)
    if (/<[A-Z][a-zA-Z]*\s/.test(storyContent) && !storyContent.includes('html`')) {
      errors.push('Using JSX syntax instead of Lit html template');
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }

  /**
   * Generate import statements for Web Components
   */
  generateImports(
    components: DiscoveredComponent[],
    config: StoryUIConfig
  ): string {
    const lib = config.importPath || 'your-library';
    const imports: string[] = ["import { html } from 'lit';"];

    // Import each component (side-effect import to register custom element)
    for (const component of components) {
      const tagName = this.toKebabCase(component.name);
      imports.push(`import '${lib}/${tagName}';`);
    }

    return imports.join('\n');
  }
}

/**
 * Factory function
 */
export function createWebComponentsAdapter(): WebComponentsAdapter {
  return new WebComponentsAdapter();
}

// story-generator/framework-adapters/angular-adapter.ts
/**
 * Angular Framework Adapter
 *
 * Generates Storybook stories for Angular components.
 * Supports standalone components and module-based components.
 */

import {
  FrameworkType,
  StoryFramework,
  StoryGenerationOptions,
} from './types.js';
import { BaseFrameworkAdapter } from './base-adapter.js';
import { StoryUIConfig } from '../../story-ui.config.js';
import { DiscoveredComponent } from '../componentDiscovery.js';

export class AngularAdapter extends BaseFrameworkAdapter {
  readonly type: FrameworkType = 'angular';
  readonly name = 'Angular';
  readonly supportedStoryFrameworks: StoryFramework[] = [
    'storybook-angular',
    'chromatic',
  ];
  readonly defaultExtension = '.stories.ts';

  generateSystemPrompt(
    config: StoryUIConfig,
    options?: StoryGenerationOptions
  ): string {
    if (config.systemPrompt) {
      return config.systemPrompt;
    }

    const componentSystemName = config.componentPrefix
      ? `${config.componentPrefix.replace(/^[A-Z]+/, '')} design system`
      : 'component library';

    return `You are an expert Angular developer creating Storybook stories using CSF 3.0 format.
Use ONLY the Angular components from the ${componentSystemName} listed below.

MANDATORY IMPORTS - First lines of every story file:
1. import type { Meta, StoryObj } from '@storybook/angular';
2. import { ComponentName } from '${config.importPath || 'your-library'}';

ANGULAR STORY FORMAT:
- Use moduleMetadata for imports and providers
- Components can be standalone or module-based
- Use applicationConfig for standalone components

STORY STRUCTURE (CSF 3.0):
- Meta object with component, title, and decorators
- Use render function for template customization
- Export named stories as StoryObj

CRITICAL RULES:
- Import modules/components in moduleMetadata or applicationConfig
- Use Angular template syntax in render functions
- Event bindings use (event) syntax

Example structure (Standalone Components):
\`\`\`typescript
import type { Meta, StoryObj } from '@storybook/angular';
import { applicationConfig, argsToTemplate } from '@storybook/angular';
import { ButtonComponent } from 'your-library';

const meta: Meta<ButtonComponent> = {
  title: 'Components/Button',
  component: ButtonComponent,
  tags: ['autodocs'],
  decorators: [
    applicationConfig({
      providers: [],
    }),
  ],
  argTypes: {
    variant: {
      control: 'select',
      options: ['primary', 'secondary', 'ghost'],
    },
  },
};

export default meta;
type Story = StoryObj<ButtonComponent>;

export const Primary: Story = {
  args: {
    variant: 'primary',
    label: 'Click me',
  },
};

export const WithContent: Story = {
  render: (args) => ({
    props: args,
    template: \`
      <app-button [variant]="variant">
        <span class="icon">★</span>
        Click me
      </app-button>
    \`,
  }),
};
\`\`\`

Example structure (Module-based Components):
\`\`\`typescript
import type { Meta, StoryObj } from '@storybook/angular';
import { moduleMetadata } from '@storybook/angular';
import { ButtonModule } from 'your-library';

const meta: Meta = {
  title: 'Components/Button',
  decorators: [
    moduleMetadata({
      imports: [ButtonModule],
    }),
  ],
  argTypes: {
    variant: {
      control: 'select',
      options: ['primary', 'secondary', 'ghost'],
    },
  },
};

export default meta;
type Story = StoryObj;

export const Primary: Story = {
  render: (args) => ({
    props: args,
    template: \`<app-button [variant]="variant">Click me</app-button>\`,
  }),
};
\`\`\`

ANGULAR TEMPLATE SYNTAX:
- Property binding: [property]="value"
- Event binding: (event)="handler($event)"
- Two-way binding: [(ngModel)]="value"
- Structural directives: *ngIf, *ngFor, *ngSwitch

CONTENT PROJECTION (ng-content):
- Default slot: Content between tags
- Named slots: Use ngProjectAs or select attribute

${this.getCommonRules()}`;
  }

  generateExamples(config: StoryUIConfig): string {
    const lib = config.importPath || 'your-library';

    return `
## Example Stories for Angular

### Standalone Component
\`\`\`typescript
import type { Meta, StoryObj } from '@storybook/angular';
import { applicationConfig } from '@storybook/angular';
import { ButtonComponent } from 'your-library';

const meta: Meta<ButtonComponent> = {
  title: 'Components/Button',
  component: ButtonComponent,
  tags: ['autodocs'],
  decorators: [
    applicationConfig({
      providers: [],
    }),
  ],
  argTypes: {
    variant: {
      control: 'select',
      options: ['primary', 'secondary', 'ghost'],
    },
    size: {
      control: 'select',
      options: ['small', 'medium', 'large'],
    },
  },
};

export default meta;
type Story = StoryObj<ButtonComponent>;

export const Default: Story = {
  args: {
    variant: 'primary',
    size: 'medium',
    label: 'Button',
  },
};

export const AllVariants: Story = {
  render: () => ({
    template: \`
      <div style="display: flex; gap: 8px;">
        <app-button variant="primary">Primary</app-button>
        <app-button variant="secondary">Secondary</app-button>
        <app-button variant="ghost">Ghost</app-button>
      </div>
    \`,
  }),
};
\`\`\`

### Module-based Component
\`\`\`typescript
import type { Meta, StoryObj } from '@storybook/angular';
import { moduleMetadata } from '@storybook/angular';
import { CardModule, ButtonModule } from '${lib}';

const meta: Meta = {
  title: 'Components/Card',
  decorators: [
    moduleMetadata({
      imports: [CardModule, ButtonModule],
    }),
  ],
};

export default meta;
type Story = StoryObj;

export const ProductCard: Story = {
  render: () => ({
    template: \`
      <app-card style="width: 300px">
        <img appCardImage src="https://picsum.photos/300/200" alt="Product">
        <h3 appCardTitle>Product Name</h3>
        <p appCardContent>$99.00</p>
        <app-button appCardAction variant="primary">Add to Cart</app-button>
      </app-card>
    \`,
  }),
};
\`\`\`

### With Event Handling
\`\`\`typescript
import type { Meta, StoryObj } from '@storybook/angular';
import { applicationConfig } from '@storybook/angular';
import { ButtonComponent } from 'your-library';

const meta: Meta<ButtonComponent> = {
  title: 'Components/Button',
  component: ButtonComponent,
  decorators: [
    applicationConfig({
      providers: [],
    }),
  ],
  argTypes: {
    // Use argTypes with action for event logging instead of addon-actions
    onClick: { action: 'clicked' },
  },
};

export default meta;
type Story = StoryObj<ButtonComponent>;

export const WithClick: Story = {
  render: (args) => ({
    props: args,
    template: \`
      <app-button (click)="onClick($event)" variant="primary">
        Click me
      </app-button>
    \`,
  }),
};
\`\`\`

### With Forms
\`\`\`typescript
import type { Meta, StoryObj } from '@storybook/angular';
import { moduleMetadata } from '@storybook/angular';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { InputModule } from '${lib}';

const meta: Meta = {
  title: 'Components/Input',
  decorators: [
    moduleMetadata({
      imports: [FormsModule, ReactiveFormsModule, InputModule],
    }),
  ],
};

export default meta;
type Story = StoryObj;

export const WithNgModel: Story = {
  render: () => ({
    props: {
      value: '',
    },
    template: \`
      <div>
        <app-input [(ngModel)]="value" placeholder="Type here..."></app-input>
        <p>Value: {{ value }}</p>
      </div>
    \`,
  }),
};
\`\`\`
`;
  }

  generateSampleStory(
    config: StoryUIConfig,
    components: DiscoveredComponent[]
  ): string {
    const lib = config.importPath || 'your-library';
    const firstComponent = components[0];

    if (!firstComponent) {
      return `
import type { Meta, StoryObj } from '@storybook/angular';

const meta: Meta = {
  title: 'Examples/Sample',
  parameters: { layout: 'centered' },
};

export default meta;
type Story = StoryObj;

export const Default: Story = {
  render: () => ({
    template: '<div>Sample story content</div>',
  }),
};
`;
    }

    // Convert PascalCase to kebab-case for selector
    const selector = this.toKebabCase(firstComponent.name);

    return `
import type { Meta, StoryObj } from '@storybook/angular';
import { applicationConfig } from '@storybook/angular';
import { ${firstComponent.name}Component } from '${lib}';

const meta: Meta<${firstComponent.name}Component> = {
  title: 'Components/${firstComponent.name}',
  component: ${firstComponent.name}Component,
  tags: ['autodocs'],
  decorators: [
    applicationConfig({
      providers: [],
    }),
  ],
  parameters: { layout: 'centered' },
};

export default meta;
type Story = StoryObj<${firstComponent.name}Component>;

export const Default: Story = {
  args: {},
};
`;
  }

  getStoryTemplate(options?: StoryGenerationOptions): string {
    return `
// {{componentName}}.stories.ts
import type { Meta, StoryObj } from '@storybook/angular';
import { applicationConfig } from '@storybook/angular';
import { {{componentName}}Component } from '{{importPath}}';

const meta: Meta<{{componentName}}Component> = {
  title: '{{category}}/{{componentName}}',
  component: {{componentName}}Component,
  tags: ['autodocs'],
  decorators: [
    applicationConfig({
      providers: [],
    }),
  ],
  parameters: { layout: 'centered' },
};

export default meta;
type Story = StoryObj<{{componentName}}Component>;

export const Default: Story = {
  args: {},
};
`;
  }

  /**
   * Convert PascalCase to kebab-case for selectors
   */
  private toKebabCase(str: string): string {
    return str
      .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
      .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
      .toLowerCase();
  }

  /**
   * Post-process Angular stories
   */
  postProcess(storyContent: string): string {
    let processed = super.postProcess(storyContent);

    // Remove React imports if present
    processed = processed.replace(/import React from ['"]react['"];?\n?/g, '');

    // Fix JSX to Angular template syntax
    processed = processed
      // Fix className to class
      .replace(/className=/g, 'class=')
      // Fix onClick to (click)
      .replace(/onClick=/g, '(click)=')
      .replace(/onChange=/g, '(change)=')
      .replace(/onInput=/g, '(input)=');

    return processed;
  }

  /**
   * Validate Angular story
   */
  validate(storyContent: string): { valid: boolean; errors: string[] } {
    const baseValidation = super.validate(storyContent);
    const errors = [...baseValidation.errors];

    // Angular-specific validations
    if (!storyContent.includes('@storybook/angular')) {
      errors.push("Missing '@storybook/angular' import");
    }

    if (storyContent.includes("import React from 'react'")) {
      errors.push('React import found in Angular story');
    }

    // Check for neither moduleMetadata nor applicationConfig
    if (
      !storyContent.includes('moduleMetadata') &&
      !storyContent.includes('applicationConfig') &&
      !storyContent.includes('component:')
    ) {
      errors.push('Missing moduleMetadata or applicationConfig decorator');
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }
}

/**
 * Factory function
 */
export function createAngularAdapter(): AngularAdapter {
  return new AngularAdapter();
}
